### ISSUE TITLE
Which OS do you use?

### ISSUE THREAD

**Issue by Invertisment** [iliazeus/durgod#1]
It would be great if you'd mention which OS you developed it for. Thanks.
Also does this expect QMK firmware or stock?

**Comment by iliazeus** [comment]
This is all for stock firmware, and is developed mostly as a reverse-engineering of the Durgod Zeus Engine software. I only really test it on Linux, but it should work on any other platforms that are supported by Python and the `pyusb` library. This has actually started because I was kinda bummed that the Zeus Engine only has a Windows version.

**Comment by iliazeus** [comment]
I will try to make it more clear in the readme.

**Comment by Invertisment** [comment]
Great. Also which variant do you test your keyboard on? Is there anything I should expect if I have k320tkl(no backlight)?
I assume it's the same layout as mine (you talk about numbers not being configured) but I ask just to be sure.

**Comment by iliazeus** [comment]
I've been testing this on the Taurus K320 Nebula (the tenkeyless RGB one). The key remapping feature should probably work on all Tauruses; not sure about the backlight.

I've updated the readme in https://github.com/iliazeus/durgod/commit/c88fd74bceb8ae9794962a2bcbe78f51f9bc6c7a.

**Comment by Invertisment** [comment]
You answered everything. I'll close this one. Thanks.

**Comment by iliazeus** [comment]
I forgot to add that the `PRODUCT_ID` is currently hard-coded, and might need to be changed for keyboards different from mine! On Linux, you can get the `VENDOR_ID:PRODUCT_ID` pair using the `lsusb` command.

**Comment by Invertisment** [comment]
I wanted to remap CapsLock to Fn and the original Fn to Super. So I think I'll need to flash to QMK anyway.

I have k320tkl white without backlight.

**Comment by iliazeus** [comment]
It is actually possible to do what you want using my scripts! On my keyboard, at least, but should work on yours too.

```python
kb.keymap[Matrix.CAPSLOCK] = Key.FN
kb.keymap[Matrix.FN] = Key.LGUI
kb.apply_keymap()
```

Just be mindful that the stock firmware may behave somewhat weirdly when actually switching to and from a custom profile when remapping the `Fn` key E.g. it detects the _press_ of `Fn`, then the layout gets switched, so it detects the _release_ of another key, and the "`Fn` is pressed" mode is still on! You can mitigate that by pressing the (key now mapped to) `Fn` once more after switching.

**Comment by Invertisment** [comment]
Also this is my info:
```
lsusb | grep 2f68
Bus 001 Device 015: ID 2f68:0082 Hoksi Technology DURGOD Taurus K320
```

**Comment by iliazeus** [comment]
Thank you! The `PRODUCT_ID` is the hexadecimal number after the `:`. For your keyboard, it is `0x0082`. I will update the `Keyboard` class to accept these IDs as parameters; for now, you can just edit it in the code.

**Comment by iliazeus** [comment]
I've updated the `Keyboard.find()` method in a98e33b7d04817dc348761ebc489f0e58a5e9db4. Now it only looks for matching `idVendor` by default, but allows to also specify the `idProduct` if you only want to work with your model.

**Comment by Invertisment** [comment]
Nice. You could've also used a set to match the USB device ID.
Anyway, I tried it and it worked.
