### ISSUE TITLE
Is there a way to assign two actions to the FN key?

### ISSUE THREAD

**Issue by Invertisment** [iliazeus/durgod#2]
For instance I'd like to assign Fn to Capslock but don't lose its functionality:

```
kb.keymap[Matrix.CAPSLOCK] = Key.FN | Key.CAPSLOCK
```
Could be shift too.

(also the tool works on my keyboard)
(and no, I don't experience problems when moving the FN key around. It seems that it behaves without any issues at all)

**Comment by Invertisment** [comment]
I think `FN` doesn't like to be joined together with other keys:
Works:
```
kb.keymap[Matrix.SCROLLLOCK] = Key.MOD_LSHIFT | Key.Z
```
Doesn't work (no shift and no Z):
```
kb.keymap[Matrix.RSHIFT] = Key.MOD_RSHIFT | Key.FN | Key.Z
```
Doesn't work (no Shift):
```
kb.keymap[Matrix.RSHIFT] = Key.MOD_RSHIFT | Key.FN
```

Does this mean that `FN` can't be assigned to be used as a multi-function key?

**Comment by iliazeus** [comment]
From what I know right now, you can only join a "regular" key with zero or more "modifier" keys (`MOD_`) constants. The `Fn` key is handled very differently from the modifier keys, so it probably can't be combined like that.

The thing you want may still be possible, though, if we (ab)use the macro system. But I haven't looked into that yet.

**Comment by iliazeus** [comment]
Sadly, I do not own a Durgod anymore, and so I'm not able to work on this library.
